domain: kaihemming.github.io
url: https://kaihemming.github.io/
baseurl: "/"

title: Kai Hemming
email: kyhemming@gmail.com
author: Kai Hemming

lang: en

plugins:
  - jekyll-seo-tag

color: "#59806b"
# disqus:
#   shortname: example-com
#
rrss:
  email: "To:kyhemming@gmail.com"
  instagram: "https://www.instagram.com/kaixhemming/"
  linkedin: "https://www.linkedin.com/in/kai-hemming/"
  github: "https://github.com/KaiHemming"
  itch: "https://kaihemming.itch.io/"

